using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class ItemSelectionSceneController : MonoBehaviour
{
    [Header("Scene")]
    public string stageSelectSceneName = "StageSelectScene";

    [Header("Temporary Debug Keys")]
    public bool enableDebugGrantKeys = true;
    public KeyCode grantSkySwordKey = KeyCode.F6;
    public KeyCode grantGreatAttractorKey = KeyCode.F7;

    [Header("Layout")]
    public Vector2 bookSize = new Vector2(1600f, 860f);
    public Vector2 footerButtonSize = new Vector2(220f, 58f);

    [Header("Colors")]
    public Color pageColor = new Color(0.82f, 0.74f, 0.56f, 0.96f);
    public Color pageShadowColor = new Color(0.13f, 0.09f, 0.06f, 0.95f);
    public Color ribbonColor = new Color(0.23f, 0.08f, 0.07f, 0.98f);
    public Color panelColor = new Color(0.08f, 0.08f, 0.10f, 0.84f);
    public Color slotColor = new Color(0.16f, 0.17f, 0.20f, 0.92f);
    public Color selectedSlotColor = new Color(0.12f, 0.24f, 0.26f, 0.96f);
    public Color lockedSlotColor = new Color(0.10f, 0.09f, 0.09f, 0.76f);
    public Color textColor = Color.white;
    public Color mutedTextColor = new Color(0.70f, 0.72f, 0.76f, 1f);
    public Color goldColor = new Color(1f, 0.78f, 0.22f, 1f);
    public Color blueColor = new Color(0.25f, 0.86f, 1f, 1f);

    private Canvas targetCanvas;
    private RectTransform uiRoot;
    private PassiveItemInventory passiveInventory;
    private PotionInventory potionInventory;

    private TextMeshProUGUI stageTitleText;
    private TextMeshProUGUI potionCountsText;
    private readonly List<TextMeshProUGUI> equippedSlotTexts = new List<TextMeshProUGUI>();
    private readonly List<PassiveRow> passiveRows = new List<PassiveRow>();

    private class PassiveRow
    {
        public PassiveItemId itemId;
        public Button button;
        public Image background;
        public TextMeshProUGUI titleText;
        public TextMeshProUGUI bodyText;
        public TextMeshProUGUI statusText;
    }

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
    private static void RegisterSceneHook()
    {
        SceneManager.sceneLoaded -= HandleSceneLoaded;
        SceneManager.sceneLoaded += HandleSceneLoaded;
        EnsureControllerForScene(SceneManager.GetActiveScene());
    }

    private static void HandleSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        EnsureControllerForScene(scene);
    }

    private static void EnsureControllerForScene(Scene scene)
    {
        if (scene.name != "ItemSelectionScene")
            return;

        if (FindFirstObjectByType<ItemSelectionSceneController>() != null)
            return;

        GameObject controllerObject = new GameObject("ItemSelectionSceneController_AutoCreated");
        controllerObject.AddComponent<ItemSelectionSceneController>();
    }

    private void Start()
    {
        ResolveReferences();
        AcceptPendingRewards();
        BuildUI();
        RefreshUI();
    }

    private void Update()
    {
        if (!enableDebugGrantKeys || passiveInventory == null)
            return;

        bool granted = false;

        if (Input.GetKeyDown(grantSkySwordKey))
            granted |= PassiveRewardManager.GrantSkySwordReward("ItemSelection debug");

        if (Input.GetKeyDown(grantGreatAttractorKey))
            granted |= PassiveRewardManager.GrantObjectiveCompletionReward("ItemSelection debug");

        if (!granted)
            return;

        AcceptPendingRewards();
        RefreshUI();
    }

    private void ResolveReferences()
    {
        GameDatabaseManager.EnsureInstance();

        passiveInventory = PassiveItemInventory.GetOrCreate();

        if (PotionInventory.Instance != null)
            potionInventory = PotionInventory.Instance;
        else
            potionInventory = FindFirstObjectByType<PotionInventory>();

        if (potionInventory == null)
        {
            GameObject potionInventoryObject = new GameObject("PotionInventory_AutoCreated");
            potionInventory = potionInventoryObject.AddComponent<PotionInventory>();
        }

        targetCanvas = FindFirstObjectByType<Canvas>();
        if (targetCanvas == null)
            targetCanvas = CreateCanvas();

        ConfigureCanvasScaler(targetCanvas);
    }

    private void AcceptPendingRewards()
    {
        if (passiveInventory == null)
            return;

        int promoted = passiveInventory.PromotePendingPassivesToOwned();
        if (promoted > 0)
            Debug.Log($"[ItemSelection] {promoted} pending passive reward(s) became available.");
    }

    private void BuildUI()
    {
        if (targetCanvas == null || uiRoot != null)
            return;

        uiRoot = CreateRect("ItemSelectionUI_AutoGenerated", targetCanvas.transform);
        uiRoot.anchorMin = Vector2.zero;
        uiRoot.anchorMax = Vector2.one;
        uiRoot.offsetMin = Vector2.zero;
        uiRoot.offsetMax = Vector2.zero;
        uiRoot.SetAsLastSibling();

        RectTransform backdrop = CreatePanel(uiRoot, "Backdrop", new Color(0.06f, 0.07f, 0.10f, 1f), Vector2.zero);
        backdrop.anchorMin = Vector2.zero;
        backdrop.anchorMax = Vector2.one;
        backdrop.offsetMin = Vector2.zero;
        backdrop.offsetMax = Vector2.zero;

        RectTransform book = CreatePanel(uiRoot, "BookFrame", pageShadowColor, bookSize);
        book.anchorMin = new Vector2(0.5f, 0.5f);
        book.anchorMax = new Vector2(0.5f, 0.5f);
        book.pivot = new Vector2(0.5f, 0.5f);
        book.anchoredPosition = Vector2.zero;

        VerticalLayoutGroup bookLayout = book.gameObject.AddComponent<VerticalLayoutGroup>();
        bookLayout.padding = new RectOffset(28, 28, 24, 24);
        bookLayout.spacing = 18f;
        bookLayout.childControlWidth = true;
        bookLayout.childControlHeight = true;
        bookLayout.childForceExpandWidth = true;
        bookLayout.childForceExpandHeight = false;

        CreateHeader(book);
        CreateBody(book);
        CreateFooter(book);
    }

    private void CreateHeader(Transform parent)
    {
        RectTransform header = CreatePanel(parent, "RibbonHeader", ribbonColor, new Vector2(0f, 96f));
        LayoutElement layout = header.gameObject.AddComponent<LayoutElement>();
        layout.minHeight = 96f;
        layout.preferredHeight = 96f;

        TextMeshProUGUI title = CreateText(header, "Title", "SPELLSTRIKE - PREPARE YOUR LOADOUT", 38f, FontStyles.Bold, textColor);
        RectTransform titleRect = title.GetComponent<RectTransform>();
        titleRect.anchorMin = Vector2.zero;
        titleRect.anchorMax = Vector2.one;
        titleRect.offsetMin = new Vector2(24f, 0f);
        titleRect.offsetMax = new Vector2(-24f, 0f);
        title.alignment = TextAlignmentOptions.Center;
    }

    private void CreateBody(Transform parent)
    {
        RectTransform body = CreateRect("Body", parent);
        LayoutElement bodyLayout = body.gameObject.AddComponent<LayoutElement>();
        bodyLayout.minHeight = 600f;
        bodyLayout.preferredHeight = 600f;

        HorizontalLayoutGroup layout = body.gameObject.AddComponent<HorizontalLayoutGroup>();
        layout.spacing = 22f;
        layout.childControlWidth = true;
        layout.childControlHeight = true;
        layout.childForceExpandWidth = false;
        layout.childForceExpandHeight = true;

        CreateStagePage(body);
        CreateItemPage(body);
    }

    private void CreateStagePage(Transform parent)
    {
        RectTransform page = CreatePanel(parent, "StagePage", pageColor, new Vector2(650f, 600f));
        LayoutElement pageLayout = page.gameObject.AddComponent<LayoutElement>();
        pageLayout.minWidth = 650f;
        pageLayout.preferredWidth = 650f;
        pageLayout.minHeight = 600f;
        pageLayout.preferredHeight = 600f;

        VerticalLayoutGroup layout = page.gameObject.AddComponent<VerticalLayoutGroup>();
        layout.padding = new RectOffset(26, 26, 26, 26);
        layout.spacing = 18f;
        layout.childControlWidth = true;
        layout.childControlHeight = true;
        layout.childForceExpandWidth = true;
        layout.childForceExpandHeight = false;

        TextMeshProUGUI heading = CreateText(page, "Heading", "Selected Stage", 24f, FontStyles.Bold, pageShadowColor);
        heading.gameObject.AddComponent<LayoutElement>().preferredHeight = 40f;

        stageTitleText = CreateText(page, "StageTitle", string.Empty, 34f, FontStyles.Bold, ribbonColor);
        stageTitleText.textWrappingMode = TextWrappingModes.Normal;
        stageTitleText.gameObject.AddComponent<LayoutElement>().preferredHeight = 110f;

        TextMeshProUGUI note = CreateText(page, "StageNote", "Choose up to 3 passive items before entering the stage. Potions are carried into battle and used from the in-game Bag.", 20f, FontStyles.Normal, new Color(0.18f, 0.12f, 0.08f, 1f));
        note.textWrappingMode = TextWrappingModes.Normal;
        note.gameObject.AddComponent<LayoutElement>().preferredHeight = 120f;

        RectTransform potionPanel = CreatePanel(page, "PotionSummaryPanel", panelColor, new Vector2(0f, 108f));
        LayoutElement potionLayout = potionPanel.gameObject.AddComponent<LayoutElement>();
        potionLayout.minHeight = 108f;
        potionLayout.preferredHeight = 108f;

        VerticalLayoutGroup potionGroup = potionPanel.gameObject.AddComponent<VerticalLayoutGroup>();
        potionGroup.padding = new RectOffset(16, 16, 12, 12);
        potionGroup.spacing = 6f;
        potionGroup.childControlWidth = true;
        potionGroup.childControlHeight = true;
        potionGroup.childForceExpandWidth = true;
        potionGroup.childForceExpandHeight = false;

        TextMeshProUGUI potionHeader = CreateText(potionPanel, "PotionHeader", "Potions", 18f, FontStyles.Bold, mutedTextColor);
        potionHeader.gameObject.AddComponent<LayoutElement>().preferredHeight = 28f;

        potionCountsText = CreateText(potionPanel, "PotionCounts", string.Empty, 22f, FontStyles.Bold, textColor);
        potionCountsText.gameObject.AddComponent<LayoutElement>().preferredHeight = 42f;
    }

    private void CreateItemPage(Transform parent)
    {
        RectTransform page = CreatePanel(parent, "ItemPage", pageColor, new Vector2(850f, 600f));
        LayoutElement pageLayout = page.gameObject.AddComponent<LayoutElement>();
        pageLayout.minWidth = 850f;
        pageLayout.preferredWidth = 850f;
        pageLayout.minHeight = 600f;
        pageLayout.preferredHeight = 600f;

        VerticalLayoutGroup layout = page.gameObject.AddComponent<VerticalLayoutGroup>();
        layout.padding = new RectOffset(26, 26, 26, 26);
        layout.spacing = 14f;
        layout.childControlWidth = true;
        layout.childControlHeight = true;
        layout.childForceExpandWidth = true;
        layout.childForceExpandHeight = false;

        TextMeshProUGUI heading = CreateText(page, "Heading", "Passive Items", 24f, FontStyles.Bold, pageShadowColor);
        heading.gameObject.AddComponent<LayoutElement>().preferredHeight = 36f;

        CreateEquippedSlots(page);
        CreatePassiveList(page);
    }

    private void CreateEquippedSlots(Transform parent)
    {
        RectTransform row = CreateRect("EquippedSlots", parent);
        LayoutElement rowLayout = row.gameObject.AddComponent<LayoutElement>();
        rowLayout.minHeight = 84f;
        rowLayout.preferredHeight = 84f;

        HorizontalLayoutGroup layout = row.gameObject.AddComponent<HorizontalLayoutGroup>();
        layout.spacing = 10f;
        layout.childControlWidth = true;
        layout.childControlHeight = true;
        layout.childForceExpandWidth = false;
        layout.childForceExpandHeight = true;

        equippedSlotTexts.Clear();
        for (int i = 0; i < 3; i++)
            equippedSlotTexts.Add(CreateEquippedSlot(row, i + 1));
    }

    private TextMeshProUGUI CreateEquippedSlot(Transform parent, int slotNumber)
    {
        RectTransform slot = CreatePanel(parent, "EquippedSlot" + slotNumber, selectedSlotColor, new Vector2(246f, 80f));
        LayoutElement layout = slot.gameObject.AddComponent<LayoutElement>();
        layout.minWidth = 246f;
        layout.preferredWidth = 246f;
        layout.minHeight = 80f;
        layout.preferredHeight = 80f;

        TextMeshProUGUI text = CreateText(slot, "Text", "Slot " + slotNumber + "\nEmpty", 18f, FontStyles.Bold, textColor);
        RectTransform textRect = text.GetComponent<RectTransform>();
        textRect.anchorMin = Vector2.zero;
        textRect.anchorMax = Vector2.one;
        textRect.offsetMin = new Vector2(12f, 8f);
        textRect.offsetMax = new Vector2(-12f, -8f);
        text.alignment = TextAlignmentOptions.Center;
        text.textWrappingMode = TextWrappingModes.Normal;
        return text;
    }

    private void CreatePassiveList(Transform parent)
    {
        RectTransform list = CreatePanel(parent, "PassiveList", panelColor, new Vector2(0f, 382f));
        LayoutElement listLayout = list.gameObject.AddComponent<LayoutElement>();
        listLayout.minHeight = 382f;
        listLayout.preferredHeight = 382f;

        VerticalLayoutGroup layout = list.gameObject.AddComponent<VerticalLayoutGroup>();
        layout.padding = new RectOffset(12, 12, 12, 12);
        layout.spacing = 10f;
        layout.childControlWidth = true;
        layout.childControlHeight = true;
        layout.childForceExpandWidth = true;
        layout.childForceExpandHeight = false;

        passiveRows.Clear();
        foreach (PassiveItemInfo item in PassiveItemCatalog.GetAllItems())
            passiveRows.Add(CreatePassiveRow(list, item));
    }

    private PassiveRow CreatePassiveRow(Transform parent, PassiveItemInfo item)
    {
        Button button = CreateButton(parent, item.id + "Row", string.Empty, slotColor, new Vector2(0f, 112f));
        LayoutElement layout = button.gameObject.AddComponent<LayoutElement>();
        layout.minHeight = 112f;
        layout.preferredHeight = 112f;

        RectTransform rowRect = button.GetComponent<RectTransform>();

        TextMeshProUGUI title = CreateText(rowRect, "Title", item.displayName, 22f, FontStyles.Bold, textColor);
        RectTransform titleRect = title.GetComponent<RectTransform>();
        titleRect.anchorMin = new Vector2(0f, 0.5f);
        titleRect.anchorMax = new Vector2(0.64f, 1f);
        titleRect.offsetMin = new Vector2(18f, -2f);
        titleRect.offsetMax = new Vector2(-8f, -10f);

        TextMeshProUGUI body = CreateText(rowRect, "Body", item.effectSummary, 16f, FontStyles.Normal, mutedTextColor);
        RectTransform bodyRect = body.GetComponent<RectTransform>();
        bodyRect.anchorMin = new Vector2(0f, 0f);
        bodyRect.anchorMax = new Vector2(0.74f, 0.54f);
        bodyRect.offsetMin = new Vector2(18f, 10f);
        bodyRect.offsetMax = new Vector2(-8f, 2f);
        body.textWrappingMode = TextWrappingModes.Normal;

        TextMeshProUGUI status = CreateText(rowRect, "Status", string.Empty, 18f, FontStyles.Bold, goldColor);
        RectTransform statusRect = status.GetComponent<RectTransform>();
        statusRect.anchorMin = new Vector2(0.72f, 0f);
        statusRect.anchorMax = new Vector2(1f, 1f);
        statusRect.offsetMin = new Vector2(8f, 0f);
        statusRect.offsetMax = new Vector2(-18f, 0f);
        status.alignment = TextAlignmentOptions.Center;
        status.textWrappingMode = TextWrappingModes.Normal;

        PassiveRow row = new PassiveRow
        {
            itemId = item.id,
            button = button,
            background = button.GetComponent<Image>(),
            titleText = title,
            bodyText = body,
            statusText = status
        };

        button.onClick.AddListener(() => HandlePassiveClicked(row.itemId));
        return row;
    }

    private void CreateFooter(Transform parent)
    {
        RectTransform footer = CreateRect("Footer", parent);
        LayoutElement footerLayout = footer.gameObject.AddComponent<LayoutElement>();
        footerLayout.minHeight = 74f;
        footerLayout.preferredHeight = 74f;

        HorizontalLayoutGroup layout = footer.gameObject.AddComponent<HorizontalLayoutGroup>();
        layout.spacing = 18f;
        layout.childAlignment = TextAnchor.MiddleRight;
        layout.childControlWidth = false;
        layout.childControlHeight = false;
        layout.childForceExpandWidth = false;
        layout.childForceExpandHeight = false;

        Button backButton = CreateButton(footer, "BackButton", "Back", panelColor, footerButtonSize);
        backButton.onClick.AddListener(OnBackPressed);

        Button continueButton = CreateButton(footer, "ContinueButton", "Continue", ribbonColor, footerButtonSize);
        continueButton.onClick.AddListener(OnContinuePressed);
    }

    private void HandlePassiveClicked(PassiveItemId itemId)
    {
        if (passiveInventory == null)
            return;

        if (!passiveInventory.HasOwnedPassive(itemId))
        {
            Debug.Log($"[ItemSelection] Passive locked: {PassiveItemCatalog.GetDisplayName(itemId)}.");
            return;
        }

        if (passiveInventory.IsEquipped(itemId))
            passiveInventory.TryUnequipPassive(itemId);
        else
            passiveInventory.TryEquipPassive(itemId);

        RefreshUI();
    }

    private void RefreshUI()
    {
        if (stageTitleText != null)
            stageTitleText.text = StageRunSelection.SelectedStageTitle;

        if (potionCountsText != null && potionInventory != null)
        {
            potionCountsText.text = $"H x{potionInventory.GetCount(PotionType.Health)}   |   P x{potionInventory.GetCount(PotionType.Cleansing)}   |   U x{potionInventory.GetCount(PotionType.PowerUp)}";
        }

        RefreshEquippedSlots();
        RefreshPassiveRows();
    }

    private void RefreshEquippedSlots()
    {
        if (passiveInventory == null)
            return;

        for (int i = 0; i < equippedSlotTexts.Count; i++)
        {
            PassiveItemId itemId = passiveInventory.GetEquippedPassive(i);
            string itemName = itemId == PassiveItemId.None ? "Empty" : PassiveItemCatalog.GetDisplayName(itemId);
            equippedSlotTexts[i].text = $"Slot {i + 1}\n{itemName}";
            equippedSlotTexts[i].color = itemId == PassiveItemId.None ? mutedTextColor : textColor;
        }
    }

    private void RefreshPassiveRows()
    {
        if (passiveInventory == null)
            return;

        foreach (PassiveRow row in passiveRows)
        {
            bool owned = passiveInventory.HasOwnedPassive(row.itemId);
            bool equipped = passiveInventory.IsEquipped(row.itemId);

            if (equipped)
            {
                row.background.color = selectedSlotColor;
                row.statusText.text = "Equipped\nClick to remove";
                row.statusText.color = blueColor;
                row.titleText.color = textColor;
                row.bodyText.color = textColor;
                row.button.interactable = true;
            }
            else if (owned)
            {
                row.background.color = slotColor;
                row.statusText.text = "Available\nClick to equip";
                row.statusText.color = goldColor;
                row.titleText.color = textColor;
                row.bodyText.color = mutedTextColor;
                row.button.interactable = true;
            }
            else
            {
                row.background.color = lockedSlotColor;
                row.statusText.text = "Locked";
                row.statusText.color = mutedTextColor;
                row.titleText.color = mutedTextColor;
                row.bodyText.color = mutedTextColor;
                row.button.interactable = true;
            }
        }
    }

    private void OnContinuePressed()
    {
        GameDatabaseManager database = GameDatabaseManager.EnsureInstance();
        database.FlushSave();

        Debug.Log($"[ItemSelection] Continuing to {StageRunSelection.SelectedStageSceneName}.");
        StageRunSelection.LoadSelectedStage();
    }

    private void OnBackPressed()
    {
        Debug.Log("[ItemSelection] Returning to Stage Select.");
        SceneManager.LoadScene(stageSelectSceneName);
    }

    private Canvas CreateCanvas()
    {
        GameObject canvasObject = new GameObject("ItemSelectionCanvas", typeof(RectTransform), typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster));
        Canvas canvas = canvasObject.GetComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 20;
        return canvas;
    }

    private void ConfigureCanvasScaler(Canvas canvas)
    {
        CanvasScaler scaler = canvas.GetComponent<CanvasScaler>();
        if (scaler == null)
            scaler = canvas.gameObject.AddComponent<CanvasScaler>();

        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920f, 1080f);
        scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;
        scaler.matchWidthOrHeight = 0.5f;

        if (canvas.GetComponent<GraphicRaycaster>() == null)
            canvas.gameObject.AddComponent<GraphicRaycaster>();
    }

    private RectTransform CreatePanel(Transform parent, string objectName, Color color, Vector2 size)
    {
        RectTransform rect = CreateRect(objectName, parent);
        rect.sizeDelta = size;
        Image image = rect.gameObject.AddComponent<Image>();
        image.color = color;
        image.raycastTarget = true;
        return rect;
    }

    private Button CreateButton(Transform parent, string objectName, string text, Color color, Vector2 size)
    {
        RectTransform rect = CreatePanel(parent, objectName, color, size);
        Image image = rect.GetComponent<Image>();
        Button button = rect.gameObject.AddComponent<Button>();
        button.targetGraphic = image;

        ColorBlock colors = button.colors;
        colors.normalColor = Color.white;
        colors.highlightedColor = new Color(1.08f, 1.08f, 1.08f, 1f);
        colors.pressedColor = new Color(0.84f, 0.84f, 0.84f, 1f);
        colors.disabledColor = new Color(0.45f, 0.45f, 0.45f, 0.72f);
        button.colors = colors;

        if (!string.IsNullOrEmpty(text))
        {
            TextMeshProUGUI label = CreateText(rect, "Text", text, 22f, FontStyles.Bold, textColor);
            RectTransform labelRect = label.GetComponent<RectTransform>();
            labelRect.anchorMin = Vector2.zero;
            labelRect.anchorMax = Vector2.one;
            labelRect.offsetMin = Vector2.zero;
            labelRect.offsetMax = Vector2.zero;
            label.alignment = TextAlignmentOptions.Center;
        }

        return button;
    }

    private RectTransform CreateRect(string objectName, Transform parent)
    {
        GameObject obj = new GameObject(objectName, typeof(RectTransform));
        RectTransform rect = obj.GetComponent<RectTransform>();
        rect.SetParent(parent, false);
        return rect;
    }

    private TextMeshProUGUI CreateText(Transform parent, string objectName, string text, float fontSize, FontStyles fontStyle, Color color)
    {
        RectTransform rect = CreateRect(objectName, parent);
        TextMeshProUGUI tmp = rect.gameObject.AddComponent<TextMeshProUGUI>();
        tmp.text = text;
        tmp.fontSize = fontSize;
        tmp.fontStyle = fontStyle;
        tmp.color = color;
        tmp.alignment = TextAlignmentOptions.MidlineLeft;
        tmp.textWrappingMode = TextWrappingModes.NoWrap;
        tmp.overflowMode = TextOverflowModes.Ellipsis;
        return tmp;
    }
}
